### ISSUE TITLE
[Bug] Amplify build fails with ReferenceError: license is not defined

### ISSUE THREAD

**Issue by pubnubcraig** [creativetimofficial/argon-dashboard-material-ui#6]
### Version
1.0.0
### Reproduction link
https://github.com/pubnubcraig/pn-toolbox-react/blob/master/package.json
### Operating System
MacOS
### Device
Brave Browser
### Browser & Version
Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) (arm64)
### Steps to reproduce
I am trying to use AWS Amplify to host my React app that use CT template. This runs fine on my local system.
I have posted to StackOverflow with details:
https://stackoverflow.com/questions/71818377/amplify-build-fails-with-referenceerror-license-is-not-defined/71818403#71818403

Suggested fix was add file location to the license. I tried many things for that. I even tried removing the gulp.js execution but I see that it wasn't the issue. 
### What is expected?
Successful build
### What is actually happening?
Error in build:
2022-04-10T16:04:21.976Z [WARNING]: ReferenceError: license is not defined
                                at Object.<anonymous> (/codebuild/output/src885439336/src/pn-toolbox-react/gulpfile.js:80:23)
                                at Module._compile (internal/modules/cjs/loader.js:1085:14)
                                at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
                                at Module.load (internal/modules/cjs/loader.js:950:32)
                                at Function.Module._load (internal/modules/cjs/loader.js:790:12)
                                at Module.require (internal/modules/cjs/loader.js:974:19)
                                at require (internal/modules/cjs/helpers.js:101:18)
                                at requireOrImport (/codebuild/output/src885439336/src/pn-toolbox-react/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
                                at execute (/codebuild/output/src885439336/src/pn-toolbox-react/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
                                at Liftoff.handleArguments (/codebuild/output/src885439336/src/pn-toolbox-react/node_modules/gulp/node_modules/gulp-cli/index.js:211:24)

---
### Additional comments
I want to be sure I am building this with proper accrediting to CT. I have a paid license.

**Comment by sajadevo** [comment]
**Hi @pubnubcraig**

Thanks for using our product, I've updated the product and now it has a new and fresh design + a new base structure that contains more reusable and scalable code.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
